// src/lib/components/widgets/WidgetFactory.svelte
<script lang="ts">
  import type { Widget } from '$lib/types/widgets';
  import ChartWidget from './ChartWidget.svelte';
  import KpiCard from './KpiCard.svelte';
  
  export let widget: Widget;
  export let isEditing = false;
  
  $: isChartType = ['line-chart', 'bar-chart', 'pie-chart'].includes(widget.type);
</script>

{#if isChartType}
  <ChartWidget {widget} {isEditing} 
    on:edit 
    on:delete 
    on:propertyChange 
    on:dataSourceChange 
    on:dataMappingChange
  />
{:else if widget.type === 'kpi-card'}
  <KpiCard {widget} {isEditing} 
    on:edit 
    on:delete 
    on:propertyChange 
    on:dataSourceChange 
    on:dataMappingChange
  />
{/if}

// components/widgets/WidgetFactory.vue
<template>
  <div class="widget-content h-full w-full overflow-hidden">
    <ChartWidget v-if="isChartType" :widget="widget" />
    <KpiCard v-else-if="widget.type === 'kpi-card'" :widget="widget" />
    <div v-else class="flex items-center justify-center h-full text-gray-400">
      <p>{{ widget.type }} - Coming soon</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { Widget } from '~/types/widgets'
import ChartWidget from './ChartWidget.vue'
import KpiCard from './KpiCard.vue'

const props = defineProps<{
  widget: Widget
}>()

const isChartType = computed(() => 
  ['line-chart', 'bar-chart', 'pie-chart'].includes(props.widget.type)
)
</script>
