// src/lib/components/builder/DashboardCanvas.svelte
<script lang="ts">
  import { dashboardStore } from '$lib/stores/dashboardStore';
  import { droppable, type DropItemEventDetail } from '$lib/actions/dnd';
  import { DEFAULT_WIDGET_HEIGHTS, DEFAULT_WIDGET_WIDTHS } from '$lib/types/widgets';
  import type { Widget, WidgetType } from '$lib/types/widgets';
  import { getWidgetLabel } from '$lib/types/widgets';
	import WidgetWrapper from './WidgetWrapper.svelte';

  // Grid settings
  let showGrid = true;
  let gridGap = 4; // Gap between grid cells in pixels

  // Calculate grid cell size based on container width
  let containerWidth = 0;
  let containerHeight = 0;
  let gridCellWidth = 0;

  $: gridCellWidth = containerWidth ? (containerWidth - ($dashboardStore.gridSize - 1) * gridGap) / $dashboardStore.gridSize : 0;

  // Handle widget drops
  function handleWidgetDrop(event: CustomEvent<DropItemEventDetail>) {
    const { getData, x, y } = event.detail;
    const widgetType = getData('widget-type') as WidgetType;
    
    if (!widgetType) return;
    
    // Calculate grid position from pixel coordinates
    const gridX = Math.floor(x / (gridCellWidth + gridGap));
    const gridY = Math.floor(y / (containerHeight / 10)); // Rough estimate for row height
    
    // Create new widget
    const newWidget: Widget = {
      id: crypto.randomUUID(),
      type: widgetType,
      title: `New ${getWidgetLabel(widgetType)}`,
      x: gridX,
      y: gridY,
      width: DEFAULT_WIDGET_WIDTHS[widgetType] || 3,
      height: DEFAULT_WIDGET_HEIGHTS[widgetType] || 2,
      dataMapping: {},
      settings: {}
    };
    
    // Add to dashboard
    dashboardStore.addWidget(newWidget);
  }

  // Handle widget selection
  function selectWidget(id: string) {
    dashboardStore.selectWidget(id);
  }

  // Measure container
  function measureContainer(node: HTMLElement) {
    const resizeObserver = new ResizeObserver(entries => {
      for (const entry of entries) {
        containerWidth = entry.contentRect.width;
        containerHeight = entry.contentRect.height;
      }
    });
    
    resizeObserver.observe(node);
    
    return {
      destroy() {
        resizeObserver.disconnect();
      }
    };
  }
</script>
<div 
  class="relative bg-gray-50 border border-gray-200 rounded-lg min-h-[600px] w-full overflow-hidden"
  use:droppable
  use:measureContainer
  on:drop-item={(event: CustomEvent) => handleWidgetDrop(event)}
  role="application"
>
  <!-- Grid background -->
  {#if showGrid && containerWidth > 0}
    <div class="absolute inset-0 pointer-events-none">
      {#each Array($dashboardStore.gridSize + 1) as _, i}
        <div 
          class="absolute top-0 bottom-0 border-r border-dashed border-gray-200"
          style="left: {i * (gridCellWidth + gridGap)}px; width: 1px;"
        ></div>
      {/each}
      
      {#each Array(20) as _, i}
        <div 
          class="absolute left-0 right-0 border-b border-dashed border-gray-200"
          style="top: {i * 40}px; height: 1px;"
        ></div>
      {/each}
    </div>
  {/if}
  
  <!-- Widgets -->
  {#each $dashboardStore.widgets.filter(w => !w.isMinimized) as widget (widget.id)}
    <WidgetWrapper 
      {widget}
      isSelected={$dashboardStore.selectedWidgetId === widget.id}
      cellWidth={gridCellWidth}
      cellHeight={40}
      gap={gridGap}
      on:select={() => selectWidget(widget.id)}
    />
  {/each}
  
  <!-- Empty state -->
  {#if $dashboardStore.widgets.length === 0}
    <div class="absolute inset-0 flex items-center justify-center text-gray-400">
      <div class="text-center">
        <p class="text-xl">Drag widgets here to build your dashboard</p>
        <p class="text-sm mt-2">Start by dragging a widget from the palette on the left</p>
      </div>
    </div>
  {/if}
</div>

// components/builder/DashboardCanvas.vue
<template>
  <div
    ref="canvasRef"
    class="dashboard-canvas relative bg-gray-50 border border-gray-200 rounded-lg min-h-[600px] w-full overflow-hidden"
    role="application"
  >
    <!-- Grid background -->
    <div v-if="showGrid && containerWidth > 0" class="absolute inset-0 pointer-events-none">
      <!-- Vertical grid lines -->
      <div
        v-for="i in gridSize + 1"
        :key="`v-${i}`"
        class="absolute top-0 bottom-0 border-r border-dashed border-gray-200"
        :style="{ left: `${(i - 1) * (gridCellWidth + gridGap)}px`, width: '1px' }"
      />
      
      <!-- Horizontal grid lines -->
      <div
        v-for="i in 20"
        :key="`h-${i}`"
        class="absolute left-0 right-0 border-b border-dashed border-gray-200"
        :style="{ top: `${(i - 1) * cellHeight}px`, height: '1px' }"
      />
    </div>

    <!-- Widgets -->
    <WidgetWrapper
      v-for="widget in visibleWidgets"
      :key="widget.id"
      :widget="widget"
      :is-selected="store.selectedWidgetId === widget.id"
      :cell-width="gridCellWidth"
      :cell-height="cellHeight"
      :gap="gridGap"
      @select="selectWidget(widget.id)"
    />

    <!-- Empty state -->
    <div
      v-if="store.widgets.length === 0"
      class="absolute inset-0 flex items-center justify-center text-gray-400"
    >
      <div class="text-center">
        <p class="text-xl">Drag widgets here to build your dashboard</p>
        <p class="text-sm mt-2">Start by dragging a widget from the palette on the left</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useResizeObserver } from '@vueuse/core'
import type { WidgetType } from '~/types/widgets'
import { DEFAULT_WIDGET_HEIGHTS, DEFAULT_WIDGET_WIDTHS, getWidgetLabel } from '~/types/widgets'
import { useDashboardStore } from '~/stores/dashboard'
import { useDroppable } from '~/composables/useDroppable'
import WidgetWrapper from './WidgetWrapper.vue'

const store = useDashboardStore()
const canvasRef = ref<HTMLElement | null>(null)

const showGrid = ref(true)
const gridGap = ref(4)
const cellHeight = ref(40)
const containerWidth = ref(0)
const containerHeight = ref(0)

const gridSize = computed(() => store.gridSize)
const visibleWidgets = computed(() => store.visibleWidgets)

const gridCellWidth = computed(() => {
  if (!containerWidth.value) return 0
  return (containerWidth.value - (gridSize.value - 1) * gridGap.value) / gridSize.value
})

const selectWidget = (id: string) => {
  store.selectWidget(id)
}

const handleWidgetDrop = (detail: any) => {
  const widgetType = detail.getData('widget-type') as WidgetType
  if (!widgetType) return

  // Calculate grid position from pixel coordinates
  const gridX = Math.floor(detail.x / (gridCellWidth.value + gridGap.value))
  const gridY = Math.floor(detail.y / cellHeight.value)

  // Create new widget
  const newWidget = {
    id: crypto.randomUUID(),
    type: widgetType,
    title: `New ${getWidgetLabel(widgetType)}`,
    x: Math.max(0, Math.min(gridX, gridSize.value - 1)),
    y: Math.max(0, gridY),
    width: DEFAULT_WIDGET_WIDTHS[widgetType] || 3,
    height: DEFAULT_WIDGET_HEIGHTS[widgetType] || 2,
    dataMapping: {},
    settings: widgetType === 'kpi-card' ? {
      value: 12500,
      target: 15000,
      format: 'currency',
      trend: 8.5
    } : {}
  }

  store.addWidget(newWidget)
}

onMounted(() => {
  const element = canvasRef.value
  if (!element) return

  // Setup drop handlers manually
  const handleDragOver = (event: DragEvent) => {
    event.preventDefault()
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'copy'
    }
    element.classList.add('drop-active')
  }

  const handleDragLeave = () => {
    element.classList.remove('drop-active')
  }

  const handleDrop = (event: DragEvent) => {
    event.preventDefault()
    element.classList.remove('drop-active')
    
    const widgetType = event.dataTransfer?.getData('widget-type') as WidgetType
    if (!widgetType) return

    const rect = element.getBoundingClientRect()
    const x = event.clientX - rect.left
    const y = event.clientY - rect.top

    handleWidgetDrop({ getData: (key: string) => event.dataTransfer?.getData(key) || null, x, y })
  }

  element.addEventListener('dragover', handleDragOver)
  element.addEventListener('dragleave', handleDragLeave)
  element.addEventListener('drop', handleDrop)

  // Measure container
  useResizeObserver(canvasRef, (entries) => {
    const entry = entries[0]
    containerWidth.value = entry.contentRect.width
    containerHeight.value = entry.contentRect.height
  })
})
</script>

<style scoped>
.dashboard-canvas {
  position: relative;
}
</style>
