// src/lib/components/builder/PropertyEditor.svelte
<script lang="ts">
  import { dashboardStore } from '$lib/stores/dashboardStore';
  
  // Get the selected widget (if any)
  $: selectedWidget = $dashboardStore.selectedWidgetId
    ? $dashboardStore.widgets.find(w => w.id === $dashboardStore.selectedWidgetId)
    : null;
    
  // Handle widget title change
  function updateTitle(event: Event) {
    const input = event.target as HTMLInputElement;
    if (selectedWidget) {
      dashboardStore.updateWidget(selectedWidget.id, {
        title: input.value
      });
    }
  }
  
  // Handle widget position/size changes
  function updateNumericProperty(property: 'x' | 'y' | 'width' | 'height', event: Event) {
    const input = event.target as HTMLInputElement;
    const value = parseInt(input.value, 10) || 0;
    
    if (selectedWidget) {
      dashboardStore.updateWidget(selectedWidget.id, {
        [property]: value
      });
    }
  }
</script>

<div class="bg-white shadow-md rounded-lg p-4">
  <h2 class="font-medium text-lg mb-4">Properties</h2>
  
  {#if selectedWidget}
    <div class="space-y-4">
      <!-- Widget Title -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1" for="widget-title">
          Widget Title
        </label>
        <input
          id="widget-title"
          type="text"
          class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
          value={selectedWidget.title}
          on:change={updateTitle}
        />
      </div>
      
      <!-- Position and Size -->
      <div class="grid grid-cols-2 gap-3">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1" for="widget-x">
            X Position
          </label>
          <input
            id="widget-x"
            type="number"
            min="0"
            class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
            value={selectedWidget.x}
            on:change={(e) => updateNumericProperty('x', e)}
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1" for="widget-y">
            Y Position
          </label>
          <input
            id="widget-y"
            type="number"
            min="0"
            class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
            value={selectedWidget.y}
            on:change={(e) => updateNumericProperty('y', e)}
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1" for="widget-width">
            Width
          </label>
          <input
            id="widget-width"
            type="number"
            min="1"
            max="12"
            class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
            value={selectedWidget.width}
            on:change={(e) => updateNumericProperty('width', e)}
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1" for="widget-height">
            Height
          </label>
          <input
            id="widget-height"
            type="number"
            min="1"
            class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
            value={selectedWidget.height}
            on:change={(e) => updateNumericProperty('height', e)}
          />
        </div>
      </div>
      
      <!-- Widget Type (read-only) -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
          Widget Type
        </label>
        <div class="px-3 py-2 border border-gray-200 bg-gray-50 rounded-md text-sm text-gray-700">
          {selectedWidget.type.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
        </div>
      </div>
      
      <!-- TODO: Data Source -->
      <!-- TODO: Widget-specific settings -->
    </div>
  {:else}
    <div class="text-gray-500 text-sm">
      <p>No widget selected</p>
      <p class="mt-2">Select a widget on the canvas to edit its properties</p>
    </div>
  {/if}
</div>

// components/builder/PropertyEditor.vue
<template>
  <v-card class="property-editor" elevation="2">
    <v-card-title class="text-lg font-medium">Properties</v-card-title>
    <v-card-text class="pa-4">
      <div v-if="selectedWidget" class="space-y-4">
        <!-- Widget Title -->
        <v-text-field
          v-model="widgetTitle"
          label="Widget Title"
          variant="outlined"
          density="compact"
          @update:model-value="updateTitle"
        />

        <!-- Position and Size -->
        <div class="grid grid-cols-2 gap-3">
          <v-text-field
            v-model.number="widgetX"
            label="X Position"
            type="number"
            variant="outlined"
            density="compact"
            min="0"
            @update:model-value="updateProperty('x', $event)"
          />

          <v-text-field
            v-model.number="widgetY"
            label="Y Position"
            type="number"
            variant="outlined"
            density="compact"
            min="0"
            @update:model-value="updateProperty('y', $event)"
          />

          <v-text-field
            v-model.number="widgetWidth"
            label="Width"
            type="number"
            variant="outlined"
            density="compact"
            min="1"
            max="12"
            @update:model-value="updateProperty('width', $event)"
          />

          <v-text-field
            v-model.number="widgetHeight"
            label="Height"
            type="number"
            variant="outlined"
            density="compact"
            min="1"
            @update:model-value="updateProperty('height', $event)"
          />
        </div>

        <!-- Widget Type (read-only) -->
        <v-text-field
          :model-value="widgetTypeLabel"
          label="Widget Type"
          variant="outlined"
          density="compact"
          readonly
          disabled
        />
      </div>

      <div v-else class="text-gray-500 text-sm">
        <p>No widget selected</p>
        <p class="mt-2">Select a widget on the canvas to edit its properties</p>
      </div>
    </v-card-text>
  </v-card>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useDashboardStore } from '~/stores/dashboard'
import { getWidgetLabel } from '~/types/widgets'

const store = useDashboardStore()

const selectedWidget = computed(() => store.selectedWidget)

const widgetTitle = ref('')
const widgetX = ref(0)
const widgetY = ref(0)
const widgetWidth = ref(1)
const widgetHeight = ref(1)

const widgetTypeLabel = computed(() => {
  if (!selectedWidget.value) return ''
  return getWidgetLabel(selectedWidget.value.type)
})

// Watch for widget selection changes
watch(selectedWidget, (widget) => {
  if (widget) {
    widgetTitle.value = widget.title
    widgetX.value = widget.x
    widgetY.value = widget.y
    widgetWidth.value = widget.width
    widgetHeight.value = widget.height
  }
}, { immediate: true })

const updateTitle = (value: string) => {
  if (selectedWidget.value) {
    store.updateWidget(selectedWidget.value.id, { title: value })
  }
}

const updateProperty = (property: 'x' | 'y' | 'width' | 'height', value: number) => {
  if (selectedWidget.value) {
    store.updateWidget(selectedWidget.value.id, { [property]: value })
  }
}
</script>

<style scoped>
.property-editor {
  height: fit-content;
}
</style>
